### ISSUE TITLE
Do Weekly Rebuilds & Releases

### ISSUE THREAD

**Issue by Azathothas** [ading2210/shimboot-binaries#1]
Hello, I am adding some of the binaries (particularly lklfuse) to https://github.com/Azathothas/Toolpacks (https://github.com/Azathothas/Toolpacks/issues/25), It would be nice if you could change [.github/workflows/build.yaml](https://github.com/ading2210/shimboot-binaries/blob/main/.github/workflows/build.yaml) :
```yaml
name: build
run-name: Build the static binaries
on:
  push: #keeping this as before
  workflow_dispatch: #so we can run it manually 
  schedule:
    - cron: '0 0 * * 0'  # This will run the workflow at 00:00 UTC every Sunday (Weekly)
```

This would trigger new builds every week and create new releases.
The main reason is that some of the sources (lklfuse) receive constant updates, and would be nice to have the latest and greatest.

And if it's feasible, specifying `x86_64-Linux` `"$(uname -m)-$(uname -s)"` for the releases would be better, in case you intend to support arm64 in the future or just make it explicitly known that the binaries are for  `x86_64-Linux`
` shimboot-binaries-x86_64-Linux.tar.gz `
Thanks!
